#!/bin/sh
### BEGIN INIT INFO
# Provides: WSVPN
# Required-Start: $network $local_fs
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: WSVPN service
# Description: Running WSVPN obfuscation service
### END INIT INFO

# Source function library.
#. /etc/init.d/functions
 START=99

##Service start/stop functions## 
start() {
    sleep 5   # make sure boot process is done, no more console msgs
    echo "Starting WSVPN..."
    pid=`ps | grep '[p]ython3 /root/wsvpn3.py' | awk '{ print $1 }'`
    if [ -z "$pid" ] 
    then
        ( /usr/bin/python3 /root/wsvpn3.py -m client -l 127.0.0.1:8000 -u wss://telefoncek.si:443/ws/vpn/ -r ) 2>&1 | logger -t $(echo $(basename $0)) &
        echo "WSVPN started" 
    else
        echo "WSVPN is already running, process ID is $pid"
    fi
#    ( /usr/bin/python3 /root/wsvpn3.py -m client -l 127.0.0.1:8000 -u wss://telefoncek.si:443/ws/vpn/ -r ) 2>&1 | logger -t $(echo $(basename $0)) &
#    echo "WSVPN started"
}

stop() {
    pid=`ps | grep '[p]ython3 /root/wsvpn3.py' | awk '{ print $1 }'`
    echo "Stopping WSVPN..."
    # echo $pid
    kill $pid
    sleep 2
    ip route del 91.185.207.171
    echo "WSVPN stoped."
    logger -t wsvpn "WSVPN stopped, route deleted"
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       logger -t wsvpn "WSVPN restarted" 
       ;;
    status)
       pid=`ps | grep '[p]ython3 /root/wsvpn3.py' | awk '{ print $1 }'`
       echo "======================================"
       [ -z "$pid" ] && echo "WSVPN is not running!" || echo "WSVPN runnig, process ID is $pid"
       echo "======================================"
       echo "WSVPN output in system log:"
       logread -e wsvpn
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
       exit 1
esac

exit 0
